import pandas as pd
import psycopg2
from psycopg2 import sql
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Database connection parameters
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT', '5432')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

def get_db_connection():
    """Establish database connection"""
    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            port=DB_PORT,
            database=DB_NAME,
            user=DB_USER,
            password=DB_PASSWORD,
            sslmode='require'
        )
        return conn
    except Exception as e:
        print(f"Failed to connect to database: {e}")
        return None

def load_excel_to_postgres(excel_file_path, table_name='black_loyalist_directory'):
    """Load data from Excel file to PostgreSQL table"""

    # Read Excel file
    try:
        df = pd.read_excel(excel_file_path, dtype=str)
        print(f"Loaded {len(df)} records from {excel_file_path}")
    except Exception as e:
        print(f"Error reading Excel file: {e}")
        return

    # Clean column names to match database schema (PascalCase)
    column_mapping = {
        'id': 'ID',
        'ref_page': 'Ref_Page',
        'book': 'Book',
        'ship_name': 'Ship_Name',
        'commander': 'Commander',
        'first_name': 'First_Name',
        'surname': 'Surname',
        'father_firstname': 'Father_FirstName',
        'father_surname': 'Father_Surname',
        'mother_firstname': 'Mother_FirstName',
        'mother_surname': 'Mother_Surname',
        'gender': 'Gender',
        'age': 'Age',
        'race': 'Race',
        'ethnicity': 'Ethnicity',
        'description': 'Description',
        'origination_port': 'Origination_Port',
        'origination_state': 'Origination_State',
        'departure_port': 'Departure_Port',
        'departure_date': 'Departure_Date',
        'arrival_port_city': 'Arrival_Port_City',
        'primary_source_1': 'Primary_Source_1',
        'primary_source_2': 'Primary_Source_2',
        'notes': 'Notes'
    }

    df.columns = [column_mapping.get(col.lower().replace(' ', '_'), col) for col in df.columns]

    # Connect to database
    conn = get_db_connection()
    if not conn:
        return

    try:
        with conn.cursor() as cur:
            # Create table if it doesn't exist (using the schema from schema_sofafeadb.sql)
            create_table_sql = f"""
            CREATE TABLE IF NOT EXISTS {table_name} (
                "ID" VARCHAR(255),
                "Ref_Page" VARCHAR(255),
                "Book" VARCHAR(255),
                "Ship_Name" VARCHAR(255),
                "Commander" VARCHAR(255),
                "First_Name" VARCHAR(255),
                "Surname" VARCHAR(255),
                "Father_FirstName" VARCHAR(255),
                "Father_Surname" VARCHAR(255),
                "Mother_FirstName" VARCHAR(255),
                "Mother_Surname" VARCHAR(255),
                "Gender" VARCHAR(255),
                "Age" VARCHAR(255),
                "Race" VARCHAR(255),
                "Ethnicity" VARCHAR(255),
                "Description" VARCHAR(255),
                "Origination_Port" VARCHAR(255),
                "Origination_State" VARCHAR(255),
                "Departure_Port" VARCHAR(255),
                "Departure_Date" VARCHAR(255),
                "Arrival_Port_City" VARCHAR(255),
                "Primary_Source_1" VARCHAR(255),
                "Primary_Source_2" VARCHAR(255),
                "Notes" TEXT
            );
            """
            cur.execute(create_table_sql)
            print(f"Ensured table {table_name} exists")

            # Clear existing data (optional - comment out if you want to append)
            cur.execute(sql.SQL("TRUNCATE TABLE {}").format(sql.Identifier(table_name)))
            print("Cleared existing data")

            # Insert data
            columns = df.columns.tolist()
            quoted_columns = [f'"{col}"' for col in columns]
            values_placeholder = ', '.join(['%s'] * len(columns))
            insert_sql = f"""INSERT INTO {table_name} ({', '.join(quoted_columns)}) VALUES ({values_placeholder})"""

            # Convert DataFrame to list of tuples, replacing NaN with None
            data_tuples = [tuple(row) for row in df.replace({pd.NA: None, float('nan'): None}).values]

            cur.executemany(insert_sql, data_tuples)
            conn.commit()

            print(f"Successfully inserted {len(data_tuples)} records into {table_name}")

    except Exception as e:
        print(f"Error loading data: {e}")
        conn.rollback()
    finally:
        conn.close()

if __name__ == "__main__":
    # Path to the Excel file generated by the scraper
    excel_file = "../Black_Loyalist_Directory_Consolidated.xlsx"

    if os.path.exists(excel_file):
        load_excel_to_postgres(excel_file)
    else:
        print(f"Excel file not found: {excel_file}")
        print("Please ensure the scraper has been run and generated the Excel file.")